[package]
name = "chatservice"
version = "0.1.0"
authors = ["edgeone <edgeone@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chatservice"
test = false
bench = false

[dependencies]
tonic = { version = "0.3.1", features = ["tls"] }
prost = "0.6"
tokio = { version = "0.2.22", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
#tokio = { version = "0.3.2", features = ["rt-multi-thread", "time", "stream", "fs", "macros", "net", "sync"] }
#==========================================================
#tokio = { version = "1.0.1", features = ["rt-multi-thread", "time", "fs", "macros", "net", "sync"] }
#tokio-stream = "0.1.0"
#==========================================================
futures = "0.3"
pickledb = "0.4.1"

[build-dependencies]
tonic-build = "0.2.0"

[profile.release]
opt-level = 'z'
lto = true # enable link time optimization

[profile.dev]
opt-level = 0
lto = false # disable link time optimization